from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('recipes/', views.recipes_index, name='recipes_index'),
  path('recipes/a', views.recipes_index_a, name='recipes_index_a'),
  path('recipes/b', views.recipes_index_b, name='recipes_index_b'),
  path('recipes/c', views.recipes_index_c, name='recipes_index_c'),
  path('recipes/d', views.recipes_index_d, name='recipes_index_d'),
  path('recipes/e', views.recipes_index_e, name='recipes_index_e'),
  path('recipes/f', views.recipes_index_f, name='recipes_index_f'),
  path('recipes/g', views.recipes_index_g, name='recipes_index_g'),
  path('recipes/h', views.recipes_index_h, name='recipes_index_h'),
  path('recipes/i', views.recipes_index_i, name='recipes_index_i'),
  path('recipes/j', views.recipes_index_j, name='recipes_index_j'),
  path('recipes/k', views.recipes_index_k, name='recipes_index_k'),
  path('recipes/l', views.recipes_index_l, name='recipes_index_l'),
  path('recipes/m', views.recipes_index_m, name='recipes_index_m'),
  path('recipes/n', views.recipes_index_n, name='recipes_index_n'),
  path('recipes/o', views.recipes_index_o, name='recipes_index_o'),
  path('recipes/p', views.recipes_index_p, name='recipes_index_p'),
  path('recipes/q', views.recipes_index_q, name='recipes_index_q'),
  path('recipes/r', views.recipes_index_r, name='recipes_index_r'),
  path('recipes/s', views.recipes_index_s, name='recipes_index_s'),
  path('recipes/t', views.recipes_index_t, name='recipes_index_t'),
  path('recipes/u', views.recipes_index_u, name='recipes_index_u'),
  path('recipes/v', views.recipes_index_v, name='recipes_index_v'),
  path('recipes/w', views.recipes_index_w, name='recipes_index_w'),
  path('recipes/x', views.recipes_index_x, name='recipes_index_x'),
  path('recipes/y', views.recipes_index_y, name='recipes_index_y'),
  path('recipes/z', views.recipes_index_z, name='recipes_index_z'),
  path('recipes/<recipe_name>/', views.recipes_detail,name='recipes_details'),
]