# Generated by Django 3.2.7 on 2022-01-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_recipe_idmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='strThumb',
            field=models.CharField(default='https://picsum.photos/200/300.jpg', max_length=255),
        ),
    ]
