# Generated by Django 3.2.7 on 2022-01-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_recipe_strthumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='strIngredient1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient10',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient11',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient12',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient13',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient14',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient15',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient16',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient17',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient18',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient19',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient20',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient6',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient7',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient8',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strIngredient9',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure10',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure11',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure12',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure13',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure14',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure15',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure16',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure17',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure18',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure19',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure20',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure6',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure7',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure8',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strMeasure9',
            field=models.CharField(default='', max_length=255),
        ),
    ]
