# Generated by Django 3.2.7 on 2022-01-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220103_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure1',
            new_name='strIngredient21',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure10',
            new_name='strIngredient22',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure11',
            new_name='strIngredient23',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure12',
            new_name='strIngredient24',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure13',
            new_name='strIngredient25',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure14',
            new_name='strIngredient26',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure15',
            new_name='strIngredient27',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure16',
            new_name='strIngredient28',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure17',
            new_name='strIngredient29',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure18',
            new_name='strIngredient30',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure19',
            new_name='strIngredient31',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure2',
            new_name='strIngredient32',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure20',
            new_name='strIngredient33',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure3',
            new_name='strIngredient34',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure4',
            new_name='strIngredient35',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure5',
            new_name='strIngredient36',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure6',
            new_name='strIngredient37',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure7',
            new_name='strIngredient38',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure8',
            new_name='strIngredient39',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='strMeasure9',
            new_name='strIngredient40',
        ),
    ]
