# Generated by Django 3.2.7 on 2022-01-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20220103_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user',
            new_name='users',
        ),
    ]
